name: update-gh-pages

on:
  workflow_run:
    workflows: [ Java CI with Gradle ]
    types: [ completed ]
    branches: [ main ]

jobs:
  generate-docs-reports:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Export project version
        run: echo "PROJECT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Run tests and generate reports
        run: ./gradlew test

      - name: Deploy site (javadocs) to GitHub Pages for current version
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          clean: true
          folder: target/site
          target-folder: docs/${{ env.PROJECT_VERSION }}/site

      - name: Deploy tests results to GitHub Pages for current version
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/reports/tests
          target-folder: docs/${{ env.PROJECT_VERSION }}/junit

      - name: Deploy jacoco report to GitHub Pages for current version
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/reports/jacoco
          target-folder: docs/${{ env.PROJECT_VERSION }}/jacoco

      - name: Deploy site (javadocs) to GitHub Pages as latest version
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
          target-folder: docs/latest/javadoc

      - name: Deploy tests results to GitHub Pages as latest version
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/reports/tests
          target-folder: docs/latest/junit

      - name: Deploy jacoco report to GitHub Pages as latest version
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/reports/jacoco
          target-folder: docs/latest/jacoco
